### PR TITLE
style: switch component style not aligned

### PR DESCRIPTION
**Pull request by zhazhazhu**

### CODE REVIEW

**Comment by baiwusanyu-c** [comment]
Is a `1px` offset crowded?
cc/ @vtrbo

**Comment by vtrbo** [comment]
> Is a `1px` offset crowded? cc/ @vtrbo

1px
image

2px
image

I think 1px offset is better. would you?

**Comment by baiwusanyu-c** [comment]
allright!

**Review by baiwusanyu-c — APPROVED** [review]

**Review by baiwusanyu-c — CHANGES_REQUESTED** [review]
Merge after update snapshot test

**Comment by vtrbo** [comment]
> Merge after update snapshot test

👌🏻

**Review by vtrbo — APPROVED** [review]

**Pull request merged**
